name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: test-runner
    steps:
    - name: test ci
      run: echo "Hello World"
