name: Fetch secrets from Vault  
  
on:  
  push:  
    branches: [ main ]  
  
jobs:  
  fetch-vault-secrets:  
    runs-on: ubuntu-latest  
  
    env:  
      VAULT_ADDR: https://vault.pliny.dev.internal.synopsys.com # replace with your Vault address  
  
    steps:  
    - name: Checkout  
      uses: actions/checkout@v4  
  
    - name: Install Vault CLI  
      run: |  
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg  
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list  
        sudo apt-get update && sudo apt-get install -y vault jq  
  
    - name: Fetch secrets from Vault  
      env:  
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }} # set this in your GitHub repo secrets  
      run: |  
        result=$(vault kv get -format=json sce-platform-engineering/kv/Shanmukh)  
        username=$(echo "$result" | jq -r '.data.data.name')  
        password=$(echo "$result" | jq -r '.data.data.password')  
        echo "Fetched username: $username"  
        echo "Fetched password: $password"  
